import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/header/Navbar";
import Footer from "../components/footer/page";
import FloatingIcon from "@/components/FloatingIcon";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "BiExON",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased  `}
    >
      <body className="min-h-full flex flex-col bg-linear-to-r from-green-200 via-green-100 to-emerald-50 text-black">

        <Navbar />

        <main className="flex-1 pt-20">
          {children}
        </main>

        <Footer />
        <FloatingIcon />
      </body>
    </html>
  );
}
