# Generated by Django 6.1.1 on 2026-09-21 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_publication'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workexperience',
            old_name='title',
            new_name='designation',
        ),
        migrations.RemoveField(
            model_name='education',
            name='end_year',
        ),
        migrations.RemoveField(
            model_name='education',
            name='start_year',
        ),
        migrations.RemoveField(
            model_name='workexperience',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='workexperience',
            name='start_date',
        ),
        migrations.AddField(
            model_name='education',
            name='timeline',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workexperience',
            name='timeline',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='employment_type',
            field=models.CharField(choices=[('full_time', 'Full-time'), ('part_time', 'Part-time'), ('contract', 'Contract'), ('internship', 'Internship'), ('others', 'Others'), ('freelance', 'Freelance')], default='full_time', max_length=20),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='skills',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
