# Generated by Django 6.1.1 on 2026-09-29 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_publication_authors_alter_publication_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='journal_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
