# Generated by Django 6.1.1 on 2026-10-06 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('type', models.CharField(choices=[('Job', 'Job'), ('Internship', 'Internship')], max_length=20)),
                ('organization', models.CharField(max_length=255)),
                ('field', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('work_mode', models.CharField(choices=[('On-site', 'On-site'), ('Hybrid', 'Hybrid'), ('Remote', 'Remote')], max_length=20)),
                ('deadline', models.DateField()),
                ('posted_date', models.DateField()),
                ('contact_email', models.EmailField(max_length=254)),
                ('description', models.TextField()),
                ('content', models.TextField()),
                ('requirements', models.JSONField(blank=True, default=list)),
            ],
        ),
    ]
